# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/refs/heads/main/json-schema/pinact.json
# pinact - https://github.com/suzuki-shunsuke/pinact
version: 3
# files:
#   - pattern: action.yaml
#   - pattern: */action.yaml

ignore_actions:
  # - name: slsa-framework/slsa-github-generator/\.github/workflows/generator_generic_slsa3\.yml
  #   ref: v\d+\.\d+\.\d+
  # - name: actions/.*
  #   ref: main
  # - name: suzuki-shunsuke/.*
  #   ref: release-.*
  - name: actions/.*
    ref: v\d+
  - name: astral-sh/.*
    ref: v\d+
  - name: dtolnay/.*
    ref: master|stable
  - name: EmbarkStudios/cargo-deny-action
    ref: v\d+
  - name: github/.*
    ref: v\d+
  - name: mozilla-actions/sccache-action
    ref: v\d+\.\d+\.\d+
  - name: Swatinem/rust-cache
    ref: v\d+
  - name: taiki-e/.*
    ref: v\d+
