---

extends: default

rules:
  comments:
    min-spaces-from-content: 1

  comments-indentation: disable  # many false alarm
  document-start: disable
  line-length: disable
  truthy: disable  # many false alarm
