name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

env:
    # setup sccache for Rust; see https://github.com/Mozilla-Actions/sccache-action
    SCCACHE_GHA_ENABLED: "true"
    RUSTC_WRAPPER: "sccache"

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          filter: tree:0

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
      - uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - run: cargo install cargo-semver-checks --locked

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # no publish to crates.io
          # CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
