name: Rust

on: [push, pull_request]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

  RUSTFLAGS: -Dwarnings

  # setup sccache for Rust; see https://github.com/Mozilla-Actions/sccache-action
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:

  check_project_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Restore lychee cache
      uses: actions/cache@v3
      with:
        path: .lycheecache
        key: cache-lychee-${{ github.sha }}
        restore-keys: cache-lychee-

    - uses: lycheeverse/lychee-action@v1
      with:
        args: "--cache --max-cache-age 1d . -v *.md"

  lint_and_doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: mozilla-actions/sccache-action@v0.0.3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - run: cargo verify-project
    - run: cargo fmt --check --all
    - run: cargo clippy --workspace -- -D warnings
    - run: cargo doc --no-deps --workspace --document-private-items


  build_and_test:
    runs-on: ubuntu-latest
    needs: lint_and_doc
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: mozilla-actions/sccache-action@v0.0.3
    - uses: dtolnay/rust-toolchain@stable

    - run: sccache --zero-stats
    - run: cargo check --workspace --future-incompat-report
    - run: cargo build --workspace --verbose
    - run: cargo test --workspace --verbose
    - run: sccache --show-stats

  build_and_test_minver:
    runs-on: ubuntu-latest
    needs: lint_and_doc
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: mozilla-actions/sccache-action@v0.0.3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly

    - run: sccache --zero-stats
    - run: cargo +nightly -Zdirect-minimal-versions update
    - run: cargo build --workspace --verbose
    - run: cargo test --workspace --verbose
    - run: sccache --show-stats
