name: min-dep-vers

on: [push, pull_request]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

  RUSTFLAGS: -Dwarnings

  # setup sccache for Rust; see https://github.com/Mozilla-Actions/sccache-action
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: mozilla-actions/sccache-action@v0.0.4
    - name: Cache Cargo dependencies
      uses: Swatinem/rust-cache@v2

    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly

    - run: cargo +nightly -Zdirect-minimal-versions update
    - run: cargo build --verbose
    - run: cargo test --verbose
